import * as FileSystem from 'expo-file-system/legacy';

const CACHE_DIR = FileSystem.documentDirectory + 'itu_cache/';
const CACHE_FILES = {
    lessons: CACHE_DIR + 'lessons.psv',
    courses: CACHE_DIR + 'courses.psv',
    plans: CACHE_DIR + 'plans.txt',
    progs: CACHE_DIR + 'progs.psv',
    bldgs: CACHE_DIR + 'bldgs.psv',
};

export class Course {
    constructor(code, title, lang, credits, ects, prereqText, type, description) {
        this.courseCode = code;
        this.courseTitle = title ? title.replaceAll("&amp;", "&").trim() : "";
        this.lang = lang;
        this.credits = credits;
        this.ects = ects;
        this.description = description ? description.replaceAll("&amp;", "&").trim() : "";
        this.lessons = [];

        const c = typeof type === 'string' ? parseFloat(type.replaceAll(",", ".")) : parseFloat(type);
        this.classRestrictions = isNaN(c) ? null : c;

        this._requirementNames = [];
        this.requirements = [];
        this._createRequirementNames(prereqText);
    }

    static createAutoGeneratedCourse(code) {
        return new Course(code, "Auto Generated Course", "", 0, 0, "", "", "");
    }

    _createRequirementNames(e) {
        this._requirementNames = [];
        if (!e || e.includes("Yok") || e.includes("planının") || e.includes("Diğer") || e.includes("Özel") || e.includes("için")) {
            return;
        }

        var s = e.replaceAll("veya", "\nveya")
                  .replaceAll("ve", "\nve")
                  .replaceAll("(", "")
                  .replaceAll(")", "")
                  .split("\n");

        for (let e = 0; e < s.length; e++) {
            var t = s[e].trim().split(" ");
            if (0 == e) {
                this._requirementNames.push([t[0] + " " + t[1]]);
                continue;
            }
            let i = t[1] + " " + t[2], r = t[0];
            "veya" == r ? this._requirementNames[this._requirementNames.length - 1].push(i) : "ve" == r && this._requirementNames.push([i]);
        }
    }

    connectCourses(helper) {
        this.requirements = [];
        for (let s = 0; s < this._requirementNames.length; s++) {
            this.requirements.push([]);
            for (let t = 0; t < this._requirementNames[s].length; t++) {
                let code = this._requirementNames[s][t];
                let c = helper.findCourseByCode(code);
                if (c) {
                    this.requirements[s].push(c);
                }
            }
        }
    }
}

export class CourseGroup {
    constructor(courses, title) {
        this.courses = courses;
        this.title = title;
    }
}

export class Programme {
    constructor(code, name, faculty, type) {
        this.code = code;
        this.name = name;
        this.faculty = faculty;
        this.programme_type = type;
    }
    getMajorRestrictionName() {
        return `${this.code}_${this.programme_type}`;
    }
}

export class Building {
    constructor(code, name, campus_name) {
        this.code = code;
        this.name = name;
        this.campus_name = campus_name;
    }
}

export class Lesson {
    constructor(crn, course_code, teachingMethod, instructor, buildings, time, day, room, capacity, enrolled, majors) {
        this.crn = crn;
        this.course_code = course_code?.trim();
        this.teachingMethod = teachingMethod?.trim();
        this.instructor = instructor?.trim();
        this.buildings = buildings;
        this.time = time?.trim();
        this.day = day?.trim();
        this.room = room?.trim();
        this.capacity = capacity;
        this.enrolled = enrolled;
        this.majors = majors;
    }
}

class ITUHelper {
    constructor() {
        this.LESSON_PATH = "https://raw.githubusercontent.com/itu-helper/data/refs/heads/main/lessons.psv";
        this.COURSE_PATH = "https://raw.githubusercontent.com/itu-helper/data/refs/heads/main/courses.psv";
        this.COURSE_PLAN_PATH = "https://raw.githubusercontent.com/itu-helper/data/refs/heads/main/course_plans.txt";
        this.PROGRAMME_CODES_PATH = "https://raw.githubusercontent.com/itu-helper/data/refs/heads/main/programme_codes.psv";
        this.BUILDING_CODES_PATH = "https://raw.githubusercontent.com/itu-helper/data/refs/heads/main/building_codes.psv";

        this._courses = [];
        this._semesters = {};
        this._programmes = [];
        this._buildings = [];
        this.coursesDict = {};

        this.isInitialized = false;
        this.initPromise = null;
    }

    async _ensureCacheDir() {
        const dirInfo = await FileSystem.getInfoAsync(CACHE_DIR);
        if (!dirInfo.exists) {
            await FileSystem.makeDirectoryAsync(CACHE_DIR, { intermediates: true });
        }
    }

    async _readCacheFile(path) {
        try {
            const info = await FileSystem.getInfoAsync(path);
            if (!info.exists) return null;
            return await FileSystem.readAsStringAsync(path);
        } catch { return null; }
    }

    async init() {
        if (this.isInitialized) return Promise.resolve();
        if (this.initPromise) return this.initPromise;

        this.initPromise = (async () => {
            try {
                await this._ensureCacheDir();

                let [lessonsTxt, coursesTxt, plansTxt, progsTxt, bldgsTxt] = await Promise.all([
                    this._readCacheFile(CACHE_FILES.lessons),
                    this._readCacheFile(CACHE_FILES.courses),
                    this._readCacheFile(CACHE_FILES.plans),
                    this._readCacheFile(CACHE_FILES.progs),
                    this._readCacheFile(CACHE_FILES.bldgs),
                ]);

                const hasCache = lessonsTxt && coursesTxt && plansTxt && progsTxt && bldgsTxt;

                if (hasCache) {
                    console.log('[ITUHelper] ✅ Cache bulundu, anında yükleniyor...');
                    this._instantiateData(lessonsTxt, coursesTxt, plansTxt, progsTxt, bldgsTxt);
                    this.isInitialized = true;

                    this._silentRefresh();
                    return;
                }

                console.log('[ITUHelper] 🌐 İlk yükleme, internet bekleniyor...');
                [lessonsTxt, coursesTxt, plansTxt, progsTxt, bldgsTxt] = await Promise.all([
                    fetch(this.LESSON_PATH).then(r => r.text()),
                    fetch(this.COURSE_PATH).then(r => r.text()),
                    fetch(this.COURSE_PLAN_PATH).then(r => r.text()),
                    fetch(this.PROGRAMME_CODES_PATH).then(r => r.text()),
                    fetch(this.BUILDING_CODES_PATH).then(r => r.text())
                ]);

                this._saveToCache(lessonsTxt, coursesTxt, plansTxt, progsTxt, bldgsTxt);
                this._instantiateData(lessonsTxt, coursesTxt, plansTxt, progsTxt, bldgsTxt);
                this.isInitialized = true;

            } catch (err) {
                console.error("ITUHelper Init Error:", err);
            }
        })();

        return this.initPromise;
    }

    async _silentRefresh() {
        try {
            const [lessonsTxt, coursesTxt, plansTxt, progsTxt, bldgsTxt] = await Promise.all([
                fetch(this.LESSON_PATH).then(r => r.text()),
                fetch(this.COURSE_PATH).then(r => r.text()),
                fetch(this.COURSE_PLAN_PATH).then(r => r.text()),
                fetch(this.PROGRAMME_CODES_PATH).then(r => r.text()),
                fetch(this.BUILDING_CODES_PATH).then(r => r.text())
            ]);

            this._saveToCache(lessonsTxt, coursesTxt, plansTxt, progsTxt, bldgsTxt);
            this._instantiateData(lessonsTxt, coursesTxt, plansTxt, progsTxt, bldgsTxt);
            console.log('[ITUHelper] 🔄 Arka plan yenilemesi tamamlandı');
        } catch (e) { }
    }

    _saveToCache(lessonsTxt, coursesTxt, plansTxt, progsTxt, bldgsTxt) {
        Promise.all([
            FileSystem.writeAsStringAsync(CACHE_FILES.lessons, lessonsTxt),
            FileSystem.writeAsStringAsync(CACHE_FILES.courses, coursesTxt),
            FileSystem.writeAsStringAsync(CACHE_FILES.plans, plansTxt),
            FileSystem.writeAsStringAsync(CACHE_FILES.progs, progsTxt),
            FileSystem.writeAsStringAsync(CACHE_FILES.bldgs, bldgsTxt),
        ]).then(() => console.log('[ITUHelper] 💾 Cache kaydedildi'))
          .catch((e) => console.error('[ITUHelper] Cache kayıt hatası:', e));
    }

    _instantiateData(lessonsTxt, coursesTxt, plansTxt, progsTxt, bldgsTxt) {
        this.lesson_lines = lessonsTxt.split("\n");
        this.course_lines = coursesTxt.split("\n");
        this.course_plan_lines = plansTxt.split("\n");
        this.programme_codes_lines = progsTxt.split("\n");
        this.building_codes_lines = bldgsTxt.split("\n");

        this._courses = [];
        this._semesters = {};
        this._programmes = [];
        this._buildings = [];
        this.coursesDict = {};

        this._createCourses();
        this._createProgrammes();
        this._createBuildings();
        this._createLessons();
        this._connectAllCourses();
        this._createSemesters();
    }

    get courses() { return this._courses; }
    get semesters() { return this._semesters; }
    get programmes() { return this._programmes; }
    get buildings() { return this._buildings; }

    _createCourses() {
        let e = this.course_lines;
        this._courses = [];
        this.coursesDict = {};
        for (let s = 0; s < e.length; s++) {
            let t = e[s].replace("\r", "");
            if (t.length == 0) continue;
            let i = t.split("|");
            if (i.length < 8) continue;
            let r = new Course(i[0], i[1], i[2], parseFloat(i[3]), parseFloat(i[4]), i[5], i[6], i[7]);
            this._courses.push(r);
            this.coursesDict[r.courseCode] = r;
        }
    }

    _createLessons() {

        const e = this.programmes, s = this.buildings;
        let t = this.lesson_lines;
        for (let i = 0; i < t.length; i++) {
            let r = t[i].replace("\r", "");
            if (r.length == 0) continue;
            let n = r.split("|"), l = n[1], h = [];
            if (n.length >= 11 && n[10] && "-" !== n[10].trim()) {
                for (const sm of n[10].split(",")) {
                    let tm = sm.trim(), found = false;
                    for (const pg of e) {
                        if (pg.getMajorRestrictionName() === tm) { h.push(pg); found = true; }
                    }
                    if (!found) { h.push(new Programme(tm, "Auto Generated Programme", "", "")); }
                }
            }
            let c = [];
            if(n[4]) {
               let o = n[4].trim().split(" ");
               for (const bl of s) {
                   for (const ol of [...o]) {
                       if (bl.code === ol.trim()) {
                           c.push(bl);
                           o.splice(o.indexOf(ol), 1);
                           if (o.length === 0) break;
                       }
                   }
               }
            }
            let u = new Lesson(n[0], l, n[2], n[3], c, n[5], n[6], n[7], n[8], n[9], h);
            let a = this.findCourseByCode(l);
            if (a) a.lessons.push(u);
        }
    }

    _createProgrammes() {
        this._programmes = [];
        let e = this.programme_codes_lines;
        for (let s = 0; s < e.length; s++) {
            let t = e[s].replace("\r", "");
            if (t.length == 0) continue;
            let i = t.split("|");
            if (i.length < 4) continue;
            let r = new Programme(i[0], i[1], i[2], i[3]);
            this._programmes.push(r);
        }
    }

    _createBuildings() {
        this._buildings = [];
        let e = this.building_codes_lines;
        for (let s = 0; s < e.length; s++) {
            let t = e[s].replace("\r", "");
            if (t.length == 0) continue;
            let i = t.split("|");
            if (i.length < 3) continue;
            let r = new Building(i[0], i[1], i[2]);
            this._buildings.push(r);
        }
    }

    _connectAllCourses() {
        this._courses.forEach(e => { e.connectCourses(this); });
    }

    findCourseByCode(e) {
        if (!e) return null;
        let s = this.coursesDict[e];
        if (s == null) {
            if ("" === e || e.includes("undefined")) return null;
            let t = e.split(" ")[0];
            if (t.length != 3 || t.toUpperCase() !== t) {
                return null;
            }
            s = Course.createAutoGeneratedCourse(e);
            s.requirements = [];
            this._courses.push(s);
            this.coursesDict[e] = s;
        }
        return s;
    }

    _createSemesters() {
        let eStr = "", sStr = "", tStr = "", currentList = [];
        this._semesters = {};
        if (!this.course_plan_lines) return;

        let r = this.course_plan_lines;
        for (let n = 0; n < r.length; n++) {
            const l = r[n].replace("\r", "").trim();
            if(!l) continue;

            if (l.startsWith("#")) {
                currentList = [];
                let prefixCount = l.split(" ")[0].length;
                let nameStr = l.slice(prefixCount + 1).trim();

                if (prefixCount == 1) {
                    eStr = nameStr;
                    this._semesters[eStr] = {};
                } else if (prefixCount == 2) {
                    if (this._semesters[eStr][sStr] && Object.keys(this._semesters[eStr][sStr]).length == 0) {
                        delete this._semesters[eStr][sStr];
                    }
                    sStr = nameStr;
                    this._semesters[eStr][sStr] = {};
                } else if (prefixCount == 3) {
                    tStr = nameStr;
                }
            } else {
                let rowArgs = [];
                let nParts = l.split("=");
                for (let idx = 0; idx < nParts.length; idx++) {
                    let sItem = nParts[idx];
                    if (sItem[0] === "[") {
                        sItem = sItem.replace("[", "").replace("]", "");
                        let sParts = sItem.split("*");
                        if(!sParts[1]) continue;
                        sParts[1] = sParts[1].replace("(", "").replace(")", "");
                        let innerCourses = sParts[1].split("|");
                        let iArr = [];
                        innerCourses.forEach(cc => {
                            if(cc) { iArr.push(this.findCourseByCode(cc)); }
                        });
                        rowArgs.push(new CourseGroup(iArr, sParts[0]));
                    } else {
                        let cf = this.findCourseByCode(sItem);
                        if (cf != null) {
                            rowArgs.push(cf);
                        }
                    }
                }
                currentList.push(rowArgs);
                if (currentList.length == 8) {
                    this._semesters[eStr][sStr][tStr] = currentList;
                }
            }
        }
    }

    getSemestersForProgramme(programmeCode) {
        const prog = this.programmes.find(p => p.code === programmeCode);
        if (!prog) return [];

        if(this.semesters[prog.faculty] && this.semesters[prog.faculty][prog.name]) {
            const plans = this.semesters[prog.faculty][prog.name];
            const planNames = Object.keys(plans);
            if(planNames.length > 0) {
                return plans[planNames[planNames.length - 1]];
            }
        }
        return [];
    }
}

const instance = new ITUHelper();
export default instance;
